version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: motel-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: motel_db
      MYSQL_USER: moteluser
      MYSQL_PASSWORD: motelpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
